services:
  app:
    build:
      context: .
      dockerfile: FrenetOrderSolution/FrenetOrder/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_URLS=http://+:80
      - TZ=America/Sao_Paulo

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "T3@te&5EC70)*"
      ACCEPT_EULA: "Y"
    restart: always